version: '3'

services:
  meilisearch:
    build:
      context: ./docker/meilisearch
      dockerfile: Dockerfile
    ports:
      - '7700:7700'
    volumes:
      - ./docker/meilisearch/data/meilisearch:/meili_data/data.ms
    environment:
      - MEILI_HTTP_ADDR=${MEILI_HTTP_ADDR}
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
