# fly.toml app configuration file generated for kidoku-search on 2023-10-04T21:51:50+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "kidoku-search"
primary_region = "nrt"

[build]

[http_service]
  internal_port = 7700
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
  processes = ["app"]
