global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - "/etc/prometheus/alert_rules.yml"

scrape_configs:
  # Prometheusのメトリクス
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporterのメトリクス（システムメトリクス）
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Next.jsアプリケーションのメトリクス
  - job_name: 'kidoku-web'
    static_configs:
      - targets: ['host.docker.internal:3000']
    metrics_path: '/api/metrics'

  # NestJS APIのメトリクス
  - job_name: 'kidoku-api'
    static_configs:
      - targets: ['host.docker.internal:4000']
    metrics_path: '/metrics'

  # MeiliSearchのメトリクス
  - job_name: 'meilisearch'
    static_configs:
      - targets: ['meilisearch:7700']
    metrics_path: '/metrics'